{{- if or .Values.podDisruptionBudget.enabled .Values.highAvailability.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "extra-codeowners.fullname" . }}
  labels:
    {{- include "extra-codeowners.labels" . | nindent 4 }}
spec:
  minAvailable: {{ if .Values.highAvailability.enabled }}{{ .Values.highAvailability.minAvailable }}{{ else }}{{ .Values.podDisruptionBudget.minAvailable }}{{ end }}
  selector:
    matchLabels:
      {{- include "extra-codeowners.applicationSelectorLabels" . | nindent 6 }}
{{- end }}
