{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "extra-codeowners.fullname" . }}
  labels:
    {{- include "extra-codeowners.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "extra-codeowners.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | quote }}
      sampleLimit: {{ .Values.monitoring.serviceMonitor.sampleLimit }}
{{- end }}
